# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('ip4address', models.GenericIPAddressField()),
                ('latitude_y', models.FloatField()),
                ('longitude_x', models.FloatField()),
                ('status', models.CharField(choices=[('UP', 'UP'), ('WARNING', 'WARNING'), ('UNREACHABLE', 'UNREACHABLE')], default='WARNING', max_length=11)),
                ('status_detail', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Hostgroup'),
        ),
    ]
