# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 2, 15, 54, 59, 311238, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
