# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_host_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip4address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='latitude_y',
            field=models.FloatField(help_text="<a href='http://mygeoposition.com/'>Lookup GeoCode</a>"),
        ),
        migrations.AlterField(
            model_name='host',
            name='longitude_x',
            field=models.FloatField(help_text="<a href='http://mygeoposition.com/'>Lookup GeoCode</a>"),
        ),
    ]
