# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='latitude_y',
            field=models.FloatField(help_text="<a href='http://mygeoposition.com/' target='_top'>Lookup GeoCode</a>"),
        ),
        migrations.AlterField(
            model_name='host',
            name='longitude_x',
            field=models.FloatField(help_text="<a href='http://mygeoposition.com/' target='_top'>Lookup GeoCode</a>"),
        ),
    ]
